### PR TITLE
Better handle BAI chunk sizes (fixes #405 and #406)

### LINKED ISSUE #405: Unable to load my local bam file in pileupjs
I have installed WAMP stack and I am trying to load a BAM file but I am getting below error.

_"q.js:161 Uncaught Monster request: Won't fetch Infinity bytes from ./test-data/molBarcode.bam"_

Am I doing something wrong here?

below is the code snippet from data.js
 
var bamSource = pileup.formats.bam({
  url: './test-data/molBarcode.bam',
  indexUrl: './test-data/molBarcode.bam.bai'
   });

### PR DESCRIPTION
**Pull request by armish**
For reasons unknown to me, some BAI files seem to have contigs of size 0. This was forcing pileup.js to try to fetch `Infinity` bytes and eventually fail. This change captures the edge case and caps the chunk size as a fix to issue #405 and #406.

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/407)

### CODE REVIEW

**Comment by armish** [comment]
looks like the `weigh_in` task doesn't work anymore. So I am removing that step from the CI while at it.

File: src/main/data/bai.js [hunk 1]
```diff
@@ -40,9 +40,7 @@ function computeIndexChunks(buffer) {
     if (n_intv) {
       var offset = VirtualOffset.fromBlob(view.getBytes(8), 0),
           coffset = offset.coffset + (offset.uoffset ? 65536 : 0);
-      if (coffset) {
-        minBlockIndex = Math.min(coffset, minBlockIndex);
-      }
+      minBlockIndex = coffset ? Math.min(coffset, minBlockIndex) : 65536;
```
Comment (ihodes) [inline src/main/data/bai.js]: What's the significance of 65536? (Maybe make a constant here instead of this magic number?)

Comment (ihodes) [inline src/main/data/bai.js]: Also, wherever this 0 was turning into infinity, may be good to assert/comment that it can't be 0 at that point.

Comment (armish) [inline src/main/data/bai.js]: Done. Thanks @ihodes! Merging this one in.
